name: big5
description: >-
    This package provides encode, decode method for big5.
    If you need a solution to encode, decode some old system
    like kk.muds, this package will help you!
version: 0.1.0
homepage: https://github.com/automihk/big5-dart
repository: https://github.com/automihk/big5-dart
issue_tracker: https://github.com/automihk/big5-dart/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  collection: ^1.18.0

dev_dependencies:
  test: ^1.24.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# This is a pure Dart package and does not require Flutter
